export const DEPARTMENTS = [
  "Business Administration",
  "Management",
  "Real Estate",
  "Tourism & Hospitality Management",
  "Innovation & Entrepreneurship",
  "Finance and Banking",
  "Accounting",
  "Marketing",
  "Computer Science & Engineering",
  "Computing & Information System (CIS)",
  "Software Engineering",
  "Environmental Science and Disaster Management",
  "Multimedia & Creative Technology (MCT)",
  "Information Technology and Management",
  "Physical Education & Sports Science (PESS)",
  "Information and Communication Engineering",
  "Textile Engineering",
  "Electrical & Electronic Engineering",
  "Architecture",
  "Civil Engineering",
  "Pharmacy",
  "Public Health",
  "Nutrition & Food Engineering",
  "Agricultural Science (AGS)",
  "Genetic Engineering and Biotechnology",
  "English",
  "Law",
  "Journalism & Mass Communication",
  "Development Studies",
  "Information Science and Library Management"
];
